### ISSUE TITLE
Incorrect output line number

### ISSUE THREAD

**Issue by MyselfYangjz** [htrgouvea/zarn#42]
At present, the main branch code still cannot output the line number correctly for the comment line。
Here is the test file I used, with the rules as default
[test.zip](https://github.com/htrgouvea/zarn/files/14755630/test.zip)
![image](https://github.com/htrgouvea/zarn/assets/132655877/59790788-8d85-4797-9e4d-7e64b962004a)

**Comment by htrgouvea** [comment]
Hi, 
ZARN performs the removal of all comments from the code during the analysis, which helps to reduce the number of false positives. Consequently, the numbering of the lines is altered. This is a problem that I can't solve at the moment and I believe it is also important. I believe this bug is acceptable as the line number is very approximate. The output also contains the line number of the variable, which helps with analysis.

**Comment by MyselfYangjz** [comment]
Hey guys, I have an idea, can you copy the source code without comments and pod documentation while checking, so that you can locate in the newly copied document, and ensure that the location is accurate, although this will add additional overhead
